# Generated by Django 6.1.1 on 2026-09-12 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(help_text='Número de serie o código interno', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Cantidad física disponible')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado (En uso)'), ('BAJA', 'Dado de baja / Inoperativo')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Responsiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibe_nombre', models.CharField(help_text='Nombre de quien recibe el artículo', max_length=150)),
                ('recibe_departamento', models.CharField(help_text='Área o departamento del empleado', max_length=100)),
                ('recibe_puesto', models.CharField(blank=True, max_length=100)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('motivo_salida', models.TextField(help_text='Razón por la cual se entrega el artículo (Asignación, reemplazo, etc.)')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
